#!/usr/bin/env bash

# Ожидание запуска RabbitMQ и скачивание утилиты управления
sleep 5
wget http://localhost:15672/cli/rabbitmqadmin
chmod +x rabbitmqadmin

echo "=== Подготовка Задания 1 (Direct Exchange) ==="
./rabbitmqadmin declare vhost name=vhost_task1
./rabbitmqadmin declare user name=sender_direct password=pass tags=management
./rabbitmqadmin declare user name=receiver_direct password=pass tags=management
./rabbitmqadmin declare permission vhost=vhost_task1 user=sender_direct configure=".*" write=".*" read=".*"
./rabbitmqadmin declare permission vhost=vhost_task1 user=receiver_direct configure=".*" write=".*" read=".*"

./rabbitmqadmin declare exchange name=ex_direct type=direct --vhost=vhost_task1
./rabbitmqadmin declare queue name=queue_direct --vhost=vhost_task1
./rabbitmqadmin declare binding source=ex_direct destination=queue_direct routing_key=key_direct --vhost=vhost_task1


echo "=== Подготовка Задания 2 (Fanout Exchange) ==="
./rabbitmqadmin declare vhost name=vhost_task2
./rabbitmqadmin declare user name=sender_fanout password=pass tags=management
./rabbitmqadmin declare user name=receiver_fanout1 password=pass tags=management
./rabbitmqadmin declare user name=receiver_fanout2 password=pass tags=management
./rabbitmqadmin declare permission vhost=vhost_task2 user=sender_fanout configure=".*" write=".*" read=".*"
./rabbitmqadmin declare permission vhost=vhost_task2 user=receiver_fanout1 configure=".*" write=".*" read=".*"
./rabbitmqadmin declare permission vhost=vhost_task2 user=receiver_fanout2 configure=".*" write=".*" read=".*"

./rabbitmqadmin declare exchange name=ex_fanout type=fanout --vhost=vhost_task2
./rabbitmqadmin declare queue name=queue_fanout_1 --vhost=vhost_task2
./rabbitmqadmin declare queue name=queue_fanout_2 --vhost=vhost_task2
./rabbitmqadmin declare binding source=ex_fanout destination=queue_fanout_1 --vhost=vhost_task2
./rabbitmqadmin declare binding source=ex_fanout destination=queue_fanout_2 --vhost=vhost_task2

echo "Брокер успешно настроен!"
